language: python
sudo: false

install:
  - pip install tox codecov

env:
  - TOX_ENV=pyflakes
  - TOX_ENV=check-manifest
  - TOX_ENV=py27-tests

# Dump trial log on failure.
after_failure: "cat _trial_temp/test.log"

script:
  - tox -c tox.ini -e $TOX_ENV

after_script:
  - codecov

# Only run test when committing to master branch.
branches:
  only:
    - master
    - \d+\.\d+\.\d+

# Do an automatic PyPi release when a tag is created.
# http://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  # twistedchecker-robot is associated with adi.roiban email address from
  # Gmail. It uses a random password which was not recorded in plain text.
  user: twistedchecker-robot
  password:
    secure: VS3uq3pdprwQUQmMFlS0ieXTX7UKvNjAQi/6CXfxqcJVlExVojsiSwOIgE76r74TuLRKDzlYD+G6dGkvaRmlfV2GVMhChUCN71Y0QtFPB68M9MuFyf/ICHb0zhs2f53/86m+ThphCOQwnOYxDeramR4TAsQR95buDO2Ko590vnQ=
  on:
    tags: true
    # All branches is still required.
    # https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
